using System;
using System.Drawing;
using System.IO.Ports;
using System.Linq;
using System.Windows.Forms;

namespace LongerControl {
    public sealed class PumpCard : UserControl {
        readonly MainForm main;readonly PumpSession pump;readonly ComboBox port;readonly Button connect,comm,refresh,start,pause,resume,stop,read,edit;readonly Label portDisplay,badge,state,error,identity,updated,detail,paramSummary;readonly Label[] metrics=new Label[4],parameterValues=new Label[13];readonly FlowChart chart;readonly ToolTip tips=new ToolTip();
        public PumpCard(MainForm main,PumpSession pump,int index){this.main=main;this.pump=pump;AutoScaleMode=AutoScaleMode.None;DoubleBuffered=true;BackColor=Color.White;Dock=DockStyle.Fill;Margin=new Padding(index==0?0:8,0,index==0?8:0,0);Padding=new Padding(16,10,16,10);
            var root=Style.Rows(34,40,23,40,23,-100,26,40);Controls.Add(root);
            var heading=Style.Columns(-100,132);heading.Controls.Add(Style.Label("0"+(index+1)+"   /   "+pump.Name,16,index==0?Style.Blue:Style.Teal),0,0);badge=Style.Label("未连接",9,Style.Muted);badge.TextAlign=ContentAlignment.MiddleRight;heading.Controls.Add(badge,1,0);root.Controls.Add(heading,0,0);
            var connection=Style.Columns(-100,46,106,92);port=new ChoiceBox{Dock=DockStyle.Fill,DropDownStyle=ComboBoxStyle.DropDownList,Margin=new Padding(0,5,8,0)};SetPortOptions(pump.Simulation?new[]{pump.Port}:SerialPort.GetPortNames(),pump.Port);port.SelectionChangeCommitted+=(s,e)=>main.SelectPort(pump,port.Text);var portBox=new BufferedPanel{Dock=DockStyle.Fill};portDisplay=Style.Label(pump.Port,10,Style.Ink);portDisplay.BackColor=Style.Canvas;portDisplay.Padding=new Padding(10,0,0,0);portDisplay.Visible=false;portBox.Controls.Add(port);portBox.Controls.Add(portDisplay);connection.Controls.Add(portBox,0,0);refresh=Make("↻",Style.Muted,null,true);refresh.Click+=(s,e)=>main.RefreshPorts();connection.Controls.Add(refresh,1,0);connect=Make("连接",Style.Blue,"link",false);connect.Click+=async(s,e)=>{if(pump.Connected)await main.DisconnectAsync(pump);else await main.ConnectAsync(pump);};connection.Controls.Add(connect,2,0);comm=Make("通信设置",Style.Muted,null,true);comm.Click+=(s,e)=>{using(var dialog=new ConnectionDialog(pump))dialog.ShowDialog(this);main.SaveConfig();Render();};connection.Controls.Add(comm,3,0);root.Controls.Add(connection,0,1);
            identity=Style.Label("LSP12-1B · 连接后读取设备身份",8,Style.Muted);root.Controls.Add(identity,0,2);
            state=Style.Label("等待连接",21,Style.Ink);root.Controls.Add(state,0,3);error=Style.Label("选择设备串口后点击连接",9,Style.Muted);root.Controls.Add(error,0,4);
            var tabs=new TabControl{Dock=DockStyle.Fill,Margin=new Padding(0,7,0,0),Padding=new Point(20,5)};var live=new TabPage("实时监测"){BackColor=Color.White,Padding=new Padding(8,6,8,0)};var parameters=new TabPage("运行参数"){BackColor=Color.White,Padding=new Padding(8,6,8,0)};tabs.TabPages.AddRange(new[]{live,parameters});root.Controls.Add(tabs,0,5);
            var liveRoot=Style.Rows(112,22,-100);live.Controls.Add(liveRoot);var metricGrid=new Grid{Dock=DockStyle.Fill,ColumnCount=2,RowCount=2};metricGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,50));metricGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,50));metricGrid.RowStyles.Add(new RowStyle(SizeType.Percent,50));metricGrid.RowStyles.Add(new RowStyle(SizeType.Percent,50));string[] names={"注射流量","累计注射","抽取流量","累计抽取"};for(int i=0;i<4;i++){var box=Style.Rows(19,-100);box.Margin=new Padding(0,0,6,4);box.BackColor=Style.Canvas;box.Padding=new Padding(10,2,0,2);box.Controls.Add(Style.Label(names[i],8,Style.Muted),0,0);metrics[i]=Style.Label("—",16,Style.Ink);box.Controls.Add(metrics[i],0,1);metricGrid.Controls.Add(box,i%2,i/2);}liveRoot.Controls.Add(metricGrid,0,0);detail=Style.Label("方向 —    线速度 —",8,Style.Muted);liveRoot.Controls.Add(detail,0,1);chart=new FlowChart();liveRoot.Controls.Add(chart,0,2);
            var paramRoot=Style.Rows(-100,34);parameters.Controls.Add(paramRoot);var paramGrid=new Grid{Dock=DockStyle.Fill,ColumnCount=2,RowCount=10,AutoScroll=true};paramGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,144));paramGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));for(int i=3;i<13;i++){paramGrid.RowStyles.Add(new RowStyle(SizeType.Absolute,25));paramGrid.Controls.Add(Style.Label(ParameterView.Names[i],8,Style.Muted),0,i-3);parameterValues[i]=Style.Label("—",9,Style.Ink);paramGrid.Controls.Add(parameterValues[i],1,i-3);}paramRoot.Controls.Add(paramGrid,0,0);var paramActions=Style.Columns(-100,120,152);paramSummary=Style.Label("以设备当前参数为准",8,Style.Muted);paramActions.Controls.Add(paramSummary,0,0);read=Make("重新读取",Style.Blue,null,true);read.Click+=async(s,e)=>await main.RunAsync(()=>pump.RefreshAsync());edit=Make("参数设置（试验）",Style.Muted,null,true);edit.Click+=async(s,e)=>await main.EditAsync(pump);paramActions.Controls.Add(read,1,0);paramActions.Controls.Add(edit,2,0);paramRoot.Controls.Add(paramActions,0,1);
            updated=Style.Label("尚无有效响应",8,Style.Muted);root.Controls.Add(updated,0,6);var actions=Style.Columns(-25,-25,-25,-25);start=Make("启动",Style.Blue,"play",false);pause=Make("暂停",Style.Ink,"pause",true);resume=Make("继续",Style.Teal,"play",true);stop=Make("停止",Style.Red,"stop",true);var actionButtons=new[]{start,pause,resume,stop};for(int i=0;i<4;i++)actions.Controls.Add(actionButtons[i],i,0);start.Click+=async(s,e)=>await main.OperateAsync(new[]{pump},PumpAction.Start,false);pause.Click+=async(s,e)=>await main.OperateAsync(new[]{pump},PumpAction.Pause,false);resume.Click+=async(s,e)=>await main.OperateAsync(new[]{pump},PumpAction.Resume,false);stop.Click+=async(s,e)=>await main.StopAsync(new[]{pump});root.Controls.Add(actions,0,7);
            tips.SetToolTip(start,"读取并确认本台泵参数后启动");tips.SetToolTip(stop,"向本台泵发送停止，并读取确认结果");tips.SetToolTip(refresh,"刷新本机串口列表");tips.SetToolTip(edit,"固件 1.0.3.0 样机拒绝参数写入；建议在泵面板设置");pump.Sampled+=sample=>chart.Add(sample);pump.Changed+=()=>{if(!pump.Connected)chart.ClearSamples();};Render();
        }
        static Button Make(string text,Color color,string symbol,bool quiet){var b=(ActionButton)Style.Button(text,color);b.Dock=DockStyle.Fill;b.Margin=new Padding(0,2,6,2);b.Symbol=symbol;b.Quiet=quiet;return b;}
        public void SetPortOptions(string[] values,string selection){
            var options=PortSelection.Sort(values).ToList();if(!string.IsNullOrEmpty(selection)&&!options.Contains(selection))options.Add(selection);
            if(port.Items.Cast<string>().SequenceEqual(options)&&port.Text==selection)return;
            port.BeginUpdate();try{port.Items.Clear();port.Items.AddRange(options.Cast<object>().ToArray());port.SelectedIndex=options.IndexOf(selection);}finally{port.EndUpdate();}
        }
        public void Render(){bool idle=!main.Working&&!pump.Busy,fresh=pump.Fresh;var snapshot=pump.Current;var status=snapshot==null?null:snapshot.Status;int current=fresh?status.State:-1;
            if(portDisplay.Visible!=pump.Connected)portDisplay.Visible=pump.Connected;if(port.Visible==pump.Connected)port.Visible=!pump.Connected;Style.Text(portDisplay,pump.Port);Style.Enabled(port,idle&&!pump.Connected);Style.Enabled(refresh,idle&&!pump.Connected);Style.Enabled(comm,idle&&!pump.Connected);Style.Enabled(connect,idle&&!main.PortDetectionInProgress);Style.Text(connect,pump.Connected?"断开":"连接");Style.Enabled(start,idle&&fresh&&status.Errors==0&&current==3);Style.Enabled(pause,idle&&fresh&&status.Errors==0&&(current==1||current==4||current==5));Style.Enabled(resume,idle&&fresh&&status.Errors==0&&current==2);Style.Enabled(stop,pump.Connected);Style.Enabled(read,idle&&pump.Connected);Style.Enabled(edit,idle&&fresh&&current==3);
            Style.Text(badge,pump.Busy?"处理中…":!pump.Connected?"未连接":fresh?"● 通信正常":"● 通信异常");Style.SetColor(badge,fresh?Style.Teal:pump.Connected?Style.Red:Style.Muted);
            Style.Text(state,!pump.Connected?"等待连接":!fresh?"状态未知":status.StateText);Style.SetColor(state,!pump.Connected?Style.Ink:!fresh||status.Errors!=0?Style.Red:current==3?Style.Ink:Style.Teal);
            string fault=pump.Error??(!pump.Connected?"选择设备串口后点击连接":!fresh?"响应已过期，请检查设备连接":status.ErrorText);Style.Text(error,fault);Style.SetColor(error,pump.Error!=null||(fresh&&status.Errors!=0)?Style.Red:Style.Muted);if(tips.GetToolTip(error)!=fault)tips.SetToolTip(error,fault);
            if(snapshot!=null){Style.Text(identity,"SN "+snapshot.Identity.Serial+"   ·   FW "+snapshot.Identity.Firmware+"   ·   "+pump.Baud+" / "+pump.Parity+" / 地址 "+pump.Address);var vals=ParameterView.Values(snapshot);for(int i=3;i<13;i++)Style.Text(parameterValues[i],vals[i]);}else{Style.Text(identity,"LSP12-1B · 连接后读取设备身份");for(int i=3;i<13;i++)Style.Text(parameterValues[i],"—");}
            if(fresh){var r=status.Raw;string[] values={Units.Flow(r[2],r[3]),Units.Volume(r[4],r[5]),Units.Flow(r[6],r[7]),Units.Volume(r[8],r[9])};for(int i=0;i<4;i++)Style.Text(metrics[i],values[i]);Style.Text(detail,"方向："+status.Direction+"     线速度："+Units.Number(((uint)r[15]<<16|r[16])*1e-7)+" mm/min");Style.Text(updated,"最近响应 "+pump.LastSample.ToLocalTime().ToString("HH:mm:ss")+"   ·   数据来自泵寄存器");}else{foreach(var m in metrics)Style.Text(m,"—");Style.Text(detail,"方向 —    线速度 —");Style.Text(updated,pump.Connected?"实时数据已失效，请查看泵面板":"尚无有效响应");}
            Style.Text(paramSummary,pump.Current==null?"尚未读取":pump.Error!=null?"参数待重新核对":"读取于 "+pump.LastConfiguration.ToLocalTime().ToString("HH:mm:ss"));
        }
        public void RefreshAvailablePorts(){main.RefreshPorts();}
        public string SelectedPort {get{return port.Text;}}
        public void CheckBounds(){foreach(Control root in Controls)if(root.Bottom>ClientSize.Height||root.Right>ClientSize.Width)throw new Exception("泵卡片布局超出边界");if(start.Height<24*main.DisplayScale||stop.Height<24*main.DisplayScale)throw new Exception("操作按钮被裁切");if(chart.Height<90*main.DisplayScale)throw new Exception("趋势图空间不足："+chart.Height);}
    }
}
